name: PI-Targeting
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - bottleneck=1.3.2
  - brotli=1.0.9
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.14.3
  - colorama=0.4.4
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - fonttools=4.25.0
  - freetype=2.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2021.4.0
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.18.1
  - jinja2=2.11.2
  - joblib=1.1.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.3.2
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp=1.2.2
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - nest-asyncio=1.4.1
  - notebook=6.1.4
  - numexpr=2.8.1
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1l
  - packaging=20.4
  - pandas=1.3.4
  - pandoc=2.11
  - pandocfilters=1.4.2
  - parso=0.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - pycparser=2.20
  - pygments=2.7.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.7.11
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - pytz=2021.3
  - pywin32=227
  - pywinpty=0.5.7
  - pyzmq=19.0.2
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - scikit-garden=0.1.3
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=58.0.4
  - sip=4.19.24
  - six=1.15.0
  - sqlite=3.37.2
  - tbb=2021.5.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=3.1.0
  - tk=8.6.11
  - tornado=6.0.4
  - traitlets=5.0.5
  - typing_extensions=3.10.0.2
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.1
  - wincertstore=0.2
  - winpty=0.4.3
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.3.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - cython==0.29.28
    - et-xmlfile==1.1.0
    - mapie==0.3.2
    - nonconformist==2.1.0
    - openpyxl==3.0.9
    - xbart==0.1.8
    - xbcausalforest==0.1.3
